### PR TITLE
Added authorisation mekasm

### PR DESCRIPTION
**Pull request by lexBogos**
All tasks including additional ones were done.

1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.ts file
3 - import-service serverless.ts file has authorizer configuration for the importProductsFile lambda.
5 - client application updated to send Authorization: Basic authorization_token header on import. Client gets authorization_token value from browser localStorage authorization_token = localStorage.getItem('authorization_token')
Additional tasks:

+1 - Client application display alerts for the responses in 401 and 403 HTTP statuses.

https://github.com/lexBogos/nodejs-aws-fe/pull/1 FE MR

Cloudfront link: https://d1sv461iq579q4.cloudfront.net/admin/products

Total 5.5/6 the issue is discrubed in the frontend MR.

### CODE REVIEW

**Comment by pavel-leskavets** [comment]
Where is the description and Front-end pull request?

**Comment by lexBogos** [comment]
> Where is the description and Front-end pull request?

Please review, I added them.

**Comment by lithiumfallen** [comment]
When I try to load `.csv` file I catch error
image

**Comment by candentira** [comment]
Same here as for @lithiumfallen 
image

**Comment by uniorunr** [comment]
Please add the correct auth token to the PR description.
Encoded **lexBogos:TEST_PASSWORD** doesn't work (`bGV4Qm9nb3M6VEVTVF9QQVNTV09SRA==`)

**Pull request merged**
